kind: ServiceAccount
apiVersion: v1
metadata:
  labels:
    app: dashboard-aggregator
  name: dashboard-aggregator-service-account
  namespace: cyberarmor-system

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dashboard-aggregator-roles
  labels:
    app: dashboard-aggregator
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "watch", "list"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dashboard-aggregator-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dashboard-aggregator-roles
subjects:
- kind: ServiceAccount
  name: dashboard-aggregator-service-account
  namespace: cyberarmor-system

---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: ca-dashboard-aggregator
  name: dashboard-aggregator-service
  namespace: cyberarmor-system
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ca-dashboard-aggregator
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ca-dashboard-aggregator
  namespace: cyberarmor-system
  labels:
    app: ca-dashboard-aggregator
spec:
  selector:
    matchLabels:
      app: ca-dashboard-aggregator
  replicas: 1
  template:
    metadata:
      labels:
        app: ca-dashboard-aggregator
    spec:
      containers:
        - name: go-aggregator
          image: dreg.eust0.cyberarmorsoft.com:443/k8s-ca-dashboard-aggregator:latest
          args:
            - -configtype=1
          env:
            - name: CA_CLUSTER_NAME
          ports:
          - containerPort: 8080
            name: aggregator-port
      imagePullSecrets:
        - name: caregcred
      serviceAccountName: dashboard-aggregator-service-account
